### PR TITLE
update help message to show GPU.1 as an argument

### PR DESCRIPTION
**Pull request by isanghao**

### CODE REVIEW

**Comment by brmarkus** [comment]
Some of the (C++) OpenVINO samples do print the "real" available devices (with the help-page), like via:

```
inline void showAvailableDevices() {
    ov::Core core;
    std::vector<std::string> devices = core.get_available_devices();

    std::cout << std::endl;
    std::cout << "Available target devices:";
    for (const auto& device : devices) {
        std::cout << "  " << device;
    }
    std::cout << std::endl;
}
```

**Comment by isanghao** [comment]
> Some of the (C++) OpenVINO samples do print the "real" available devices (with the help-page), like via:
> 
> ```
> inline void showAvailableDevices() {
>     ov::Core core;
>     std::vector<std::string> devices = core.get_available_devices();
> 
>     std::cout << std::endl;
>     std::cout << "Available target devices:";
>     for (const auto& device : devices) {
>         std::cout << "  " << device;
>     }
>     std::cout << std::endl;
> }
> ```

**Comment by isanghao** [comment]
> Some of the (C++) OpenVINO samples do print the "real" available devices (with the help-page), like via:
> 
> ```
> inline void showAvailableDevices() {
>     ov::Core core;
>     std::vector<std::string> devices = core.get_available_devices();
> 
>     std::cout << std::endl;
>     std::cout << "Available target devices:";
>     for (const auto& device : devices) {
>         std::cout << "  " << device;
>     }
>     std::cout << std::endl;
> }
> ```

@brmarkus  Thanks for the comment, updated.

**Comment by isanghao** [comment]
@brmarkus PR is updated to a new one: https://github.com/bes-dev/stable_diffusion.openvino/pull/124

**Pull request closed without merging**
